### ISSUE TITLE
[0.3] Server thread freezes while waiting for chunk structure

### ISSUE THREAD

**Issue by noiverre** [Tonnanto/BasicQuests#5] opened 2022-07-20 05:04 UTC
How to reproduce:
1. Update to 0.3 from 0.2.1
2. Get structure related quests

Log:
https://paste.gg/p/anonymous/a1c64ecd63b8466cb07f722b4a7ead9c

**Comment by Tonnanto** [comment] 2022-07-20 08:09
Thanks a lot for your report noiverre. 
Unfortunately I was not able to reproduce the issue :/fortunately I was not able to reproduce the issue :/
I used Paper 1.19 #61 and upgraded from BQ 0.2.1 to 0.3. Find structure quests worked on both versions without problems.

Some information that might help figuring this out: 
- How many players were online during the time?
- What other plugins do you have installed?
- What version was your world generated on?

**Comment by Tonnanto** [comment] 2022-07-20 08:14
Found this in the [documentation](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/World.html#locateNearestStructure(org.bukkit.Location,org.bukkit.generator.structure.Structure,int,boolean)): 

> Finding unexplored structures can, and will, block if the world is looking in chunks that gave not generated yet. This can lead to the world temporarily freezing while locating an unexplored structure.

I might need to reduce the searching radius or add some kind of timeout. But first I will need to be able to reproduce the issue :)

**Comment by noiverre** [comment] 2022-07-20 09:20
> Thanks a lot for your report noiverre. Unfortunately I was not able to reproduce the issue :/ I used Paper 1.19 #61 and upgraded from BQ 0.2.1 to 0.3. Find structure quests worked on both versions without problems.
> 
> Some information that might help figuring this out:
> 
> * How many players were online during the time?
> * What other plugins do you have installed?
> * What version was your world generated on?

It was 4 players, the other plugin that involves world and chunks are Worldguard, FAWE, Multiverse, [BetterStructures](https://www.spigotmc.org/resources/betterstructures.103241/), [Infinite Parkour](https://github.com/Efnilite/Walk-in-the-Park/)

The world was generated in 1.18.2 Paper server and upgraded to 1.19.0

**Comment by Tonnanto** [comment] 2022-07-26 19:44
I was able to reproduce your issue after adding all the plugins you mentioned :)
I greatly reduced the radius in which BasicQuests searches for nearby structures for find structure quests.
This did indeed remove the issue on my setup. It should really improve performance without impacting the detection of found structures.
Please let me know if v0.3.1 of BasicQuests fixes this issue on your server!

**Comment by Tonnanto** [comment] 2023-03-28 15:19
This issue seems to not have appeared since version 0.3.1.
I am going to close the issue as it seems to be fixed. Feel free to reopen it if it appears again :)

**Closed by Tonnanto** 2023-03-28 15:19 UTC
